name: CI-TEST
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sVersion: ["1.25.x", "1.26.x", "1.27.x", "1.28.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}    
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make ci-test
    - name: Send coverage
      # should only send converage once https://docs.coveralls.io/parallel-builds
      if: matrix.k8sVersion == '1.27.x'
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
