name: ResolveArgs
on:
  workflow_call:
    outputs:
      GIT_REF:
        value: ${{ jobs.resolve.outputs.GIT_REF }}
jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      GIT_REF: ${{ steps.resolve-step.outputs.GIT_REF }}
    steps:
      # Download the artifact and resolve the GIT_REF
      - uses: actions/checkout@v4
      - if: github.event_name == 'workflow_run'
        uses: ./.github/actions/download-artifact
      - id: resolve-step
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo GIT_REF="$(tail -n 1 /tmp/artifacts/metadata.txt)" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo GIT_REF="${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo GIT_REF="" >> "$GITHUB_OUTPUT"
          fi
